package com.vnext.entity;

public enum NotificationType {
    SUPER_ADMIN_LOGIN,
    COMPANY_ADMIN_LOGIN,
    COMPANY_CREATED,
    COMPANY_UPDATED,
    COMPANY_DELETED,
    COMPANY_STATUS_CHANGED,
    SUBSCRIPTION_EXTENDED,
    COMPLIANCE_CREATED,
    SUB_COMPLIANCE_CREATED,
    COMPLIANCE_CONFIG_UPDATED,
    COMPLIANCE_DELETED,
    SUB_COMPLIANCE_DELETED,
    COMPANY_ASSIGNED_TO_COMPLIANCE,
    COMPANY_REMOVED_FROM_COMPLIANCE,
    COMPLIANCE_ASSIGNMENT_UPDATED,
    SYSTEM_ANNOUNCEMENT,
    COMPLIANCE_COMPLETED,
    CUSTOM_COMPLIANCE_CREATED,
    COMPLIANCE_DUE_SOON,
    COMPLIANCE_OVERDUE,
    EMPLOYEE_LOGIN,
    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_DELETED
}